name=MicroRemoteWire
version=0.0.1
author=Thomas O Fredericks
maintainer=https://github.com/thomasfredericks
sentence=Small library framework that allows one I2C/Wire controller device to control a peripheral device
paragraph=...
category=Communication
url=https://github.com/thomasfredericks/MicroRemoteWire
architectures=*
includes=MicroRemoteWire.h
depends=
