name=MicroRemoteWire
version=0.0.2
author=Thomas O Fredericks
maintainer=https://github.com/thomasfredericks
sentence=Small library framework that allows one I2C/Wire controller device to control a peripheral device
paragraph=Library provides a class for a Controller device and a class for a peripheral device. The controller device can send commands to the peripheral device, which can then execute those commands. This allows for communication between devices using the I2C/Wire protocol.
category=Communication
url=https://github.com/thomasfredericks/MicroRemoteWire
architectures=*
includes=MicroRemoteWire.h
depends=
