[platformio]
; Tell PIO to treat this folder (containing .ino) as the source directory
src_dir = .


[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
lib_deps = 
    https://github.com/thomasfredericks/MicroRemoteWire
    https://github.com/thomasfredericks/MicroNet
    https://github.com/thomasfredericks/MicroOsc
    FastLED